---
build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:12.0.0
  amd64: ghcr.io/hassio-addons/base/amd64:12.0.0
  armhf: ghcr.io/hassio-addons/base/armhf:12.0.0
  armv7: ghcr.io/hassio-addons/base/armv7:12.0.0
  i386: ghcr.io/hassio-addons/base/i386:12.0.0
args:
  CLI_VERSION: 4.18.0
